Resume-Projects/Band-Inventory/Inventory/Inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from instruments import views as instrument_view
from students import views as student_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', instrument_view.home_view, name='home'),  # Set the root URL to the homepage in the instruments app
    path('', include('students.urls', namespace='students')),  # Add 'namespace' here
    path('', include('instruments.urls', namespace='instruments')),
    path('', include('checkout.urls', namespace='checkout')),
]

Resume-Projects/Band-Inventory/Inventory/checkout/urls.py
from django.urls import path
from . import views

app_name = 'checkout'

urlpatterns = [
    path('checkout/', views.checkout_index, name='checkout_index'),
    path('checkout/add/', views.add_checkout, name='add_checkout'),
    path('checkout/<int:checkout_id>/', views.view_checkout, name='view_checkout'),
    path('checkout/<int:checkout_id>/edit/', views.edit_checkout, name='edit_checkout'),
]

Resume-Projects/Band-Inventory/Inventory/instruments/urls.py
from django.urls import path
from . import views

app_name = 'instruments'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('instruments/', views.instrument_index, name='instrument_index'),
    path('instruments/add/', views.add_instrument, name='add_instrument'),
    path('instruments/<int:instrument_id>/', views.view_instrument, name='view_instrument'),
    path('instruments/<int:instrument_id>/edit/', views.edit_instrument, name='edit_instrument'),
    path('instruments/delete/', views.delete_index, name='delete_index'),
] 

Resume-Projects/Band-Inventory/Inventory/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path("students/", views.student_index, name='student_index'),
    path('students/add/', views.add_student, name='add_student'),
    path('students/<int:student_id>/', views.view_student, name='view_student'),
    path('students/<int:student_id>/edit/', views.edit_student, name='edit_student'),
]

Resume-Projects/Band-Inventory/Inventory/instruments/models.py
from django.db import models

# Create your models here.

class Instrument(models.Model):
    id = models.AutoField(primary_key=True, blank=False)
    type = models.CharField(max_length=50, blank=False)
    serial_num = models.CharField(max_length=50, blank=True)
    maker = models.CharField(max_length=50, blank=False)
    notes = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return f"{self.id} | {self.maker} {self.type}"

Resume-Projects/Band-Inventory/Inventory/instruments/forms.py
from django import forms
from .models import Instrument

class InstrumentForm(forms.ModelForm):
    class Meta:
        model = Instrument
        fields = ['type', 'serial_num', 'maker', 'notes']

Resume-Projects/Band-Inventory/Inventory/instruments/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse

from .forms import InstrumentForm
from .models import Instrument

# Create your views here.

# Home view for the "website"
def home_view(request):
    return render(request, 'instruments/home.html')

def sort_by_id(instrument):
    return instrument.id

def sort_by_type(instrument):
    return instrument.type.lower()

def sort_by_serial_num(instrument):
    return int(instrument.serial_num)

def sort_by_maker(instrument):
    return instrument.maker.lower()

def instrument_index(request):
    sort_by = request.GET.get('sort_by', 'id')
    reverse_sort = request.GET.get('reverse', 'false') == 'true'

    instruments = Instrument.objects.all()

    sorting_functions = {
        'id': sort_by_id,
        'type': sort_by_type,
        'serial': sort_by_serial_num,
        'maker': sort_by_maker,
    }

    sorting_function = sorting_functions.get(sort_by, sort_by_id)

    instruments = sorted(instruments, key=sorting_function, reverse=reverse_sort)

    context = {
        "instruments": instruments
    }

    return render(request, "instruments/index.html", context)

def add_instrument(request):
    if request.method == 'POST':
        form = InstrumentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('instruments:instrument_index')
    else:
        form = InstrumentForm()
    return render(request, 'instruments/add_instrument.html', {'form': form})

def view_instrument(request, instrument_id):
    instrument = get_object_or_404(Instrument, pk=instrument_id)
    return render(request, 'instruments/view_instrument.html', {'instrument': instrument})

def edit_instrument(request, instrument_id):
    instrument = get_object_or_404(Instrument, pk=instrument_id)
    if request.method == 'POST':
        form = InstrumentForm(request.POST, instance=instrument)
        if form.is_valid():
            form.save()
            return redirect('instruments:view_instrument', instrument_id=instrument_id)
    else:
        form = InstrumentForm(instance=instrument)
    return render(request, 'instruments/edit_instrument.html', {'form': form, 'instrument': instrument})

def delete_index(request):
    if request.method == 'POST':
        selected_instruments = request.POST.getlist('instrument_ids')

        if selected_instruments:
            selected_instruments = [int(id) for id in selected_instruments]
            Instrument.objects.filter(id__in=selected_instruments).delete()
            return redirect('instruments:instrument_index')

    instruments = Instrument.objects.all()

    context = {
        "instruments": instruments
    }

    return render(request, 'instruments/delete_index.html', context)

Resume-Projects/Band-Inventory/Inventory/instruments/templates/instruments/add_instrument.html
{% extends 'base.html' %}

{% block header %}
    <h1>Add Instrument</h1>
    <a href="{% url 'instruments:instrument_index' %}">Back to Instrument List</a>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

Resume-Projects/Band-Inventory/Inventory/instruments/templates/instruments/delete_index.html
{% extends 'base.html' %}

{% block header %}
    <h1>Instrument Deletion</h1>
    <a href="{% url 'instruments:instrument_index' %}">Back to Instruments</a>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <table>
            <thead>
                <tr>
                    <th>
                        <button type="submit" class="">Delete Selected Instruments</button>
                    </th>
                    <th>
                        <button id="sort_by_id" onclick="sortTable('id')">ID</button>
                    </th>
                    <th>
                        <button id="sort_by_type" onclick="sortTable('type')">Type</button>
                    </th>
                    <th>
                        <button id="sort_by_serial_num" onclick="sortTable('serial')">Serial Number</button>
                    </th>
                    <th>
                        <button id="sort_by_maker" onclick="sortTable('maker')">Maker</button>
                    </th>
                    <th>
                        <button id="sort_by_notes" onclick="sortTable('notes')">Notes</button>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for instrument in instruments %}
                    <tr>
                        <td><input type="checkbox" name="instrument_ids" value="{{ instrument.id }}"></td>
                        <td><a href="{% url 'instruments:view_instrument' instrument.id %}">{{ instrument.id }}</a></td>
                        <td>{{ instrument.type }}</td>
                        <td>{{ instrument.serial_num }}</td>
                        <td>{{ instrument.maker }}</td>
                        <td>{{ instrument.notes }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="5">No instruments available.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </form>
    <script>
        function sortTable(sortBy) {
            var url = new URL(window.location.href);
            var params = new URLSearchParams(url.search);
    
            if (params.get('sort_by') === sortBy) {
                // Toggle the reverse sorting order
                params.set('reverse', params.get('reverse') === 'true' ? 'false' : 'true');
            } else {
                // Set the sorting attribute and default to ascending order
                params.set('sort_by', sortBy);
                params.set('reverse', 'false');
            }
    
            // Update the URL with the new parameters
            if (url.pathname.endsWith('delete/')) {
                // If you're on the delete_index page, use a different URL path
                window.location.href = '/instruments/delete/?' + params.toString();
            } else {
                // Use the same URL path as in other cases
                window.location.href = '?' + params.toString();
            }
        }
    </script>
    
{% endblock %}

Resume-Projects/Band-Inventory/Inventory/instruments/templates/instruments/edit_instrument.html
{% extends 'base.html' %}

{% block header %}
    <h1>Edit Instrument</h1>
    <a href="{% url 'instruments:view_instrument' instrument.id %}">View Details</a>
    <a href="{% url 'instruments:instrument_index' %}">Back to Instrument List</a>
{% endblock %}

{% block content %}
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
    
{% endblock %}

Resume-Projects/Band-Inventory/Inventory/instruments/templates/instruments/home.html
{% load static %}
{% block content %}
<style>
    .piece {
        text-align: center;
    }
</style>
<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
    <h1 class="piece">Welcome to the Inventory App</h1>
    <div class="piece">
        <button onclick="goToStudents()">Students</button>
        <button onclick="goToInstruments()">Instruments</button>
        <button onclick="goToCheckout()">Checkout</button>
    </div>

    <script>
        // Define JavaScript functions to route to URLs
        function goToStudents() {
            // Use JavaScript to navigate to the Students page
            window.location.href = "{% url 'students:student_index' %}";
        }
    
        function goToInstruments() {
            // Use JavaScript to navigate to the Instruments page
            window.location.href = "{% url 'instruments:instrument_index' %}";
        }

        function goToCheckout() {
            // Use JavaScript to navigate to the Instruments page
            window.location.href = "{% url 'checkout:checkout_index' %}";
        }
        
    </script>
{% endblock %}

Resume-Projects/Band-Inventory/Inventory/instruments/templates/instruments/index.html
{% extends 'base.html' %}

{% block header %}
    <h1>Instruments</h1>
    <a href="{% url 'instruments:add_instrument' %}">Add Instrument</a>
    <a href="{% url 'instruments:delete_index' %}">Delete Instrument</a>
{% endblock %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>
                    <button id="sort_by_id" onclick="sortTable('id')">ID</button>
                </th>
                <th>
                    <button id="sort_by_type" onclick="sortTable('type')">Type</button>
                </th>
                <th>
                    <button id="sort_by_serial_num" onclick="sortTable('serial')">Serial Number</button>
                </th>
                <th>
                    <button id="sort_by_maker" onclick="sortTable('maker')">Maker</button>
                </th>
                <th>
                    <button id="sort_by_notes" onclick="sortTable('notes')">Notes</button>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for instrument in instruments %}
                <tr>
                    <td><a href="{% url 'instruments:view_instrument' instrument.id %}">{{ instrument.id }}</a></td>
                    <td>{{ instrument.type }}</td>
                    <td>{{ instrument.serial_num }}</td>
                    <td>{{ instrument.maker }}</td>
                    <td>{{ instrument.notes }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5">No instruments available.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script>
        function sortTable(sortBy) {
            var url = new URL(window.location.href);
            var params = new URLSearchParams(url.search);

            if (params.get('sort_by') === sortBy) {
                // Toggle the reverse sorting order
                params.set('reverse', params.get('reverse') === 'true' ? 'false' : 'true');
            } else {
                // Set the sorting attribute and default to ascending order
                params.set('sort_by', sortBy);
                params.set('reverse', 'false');
            }

            // Update the URL with the new parameters
            window.location.href = '?' + params.toString();
        }
    </script>
{% endblock %}

Resume-Projects/Band-Inventory/Inventory/instruments/templates/instruments/view_instrument.html
{% extends 'base.html' %}

{% block header %}
    <h1>Instrument Details</h1>
    <a href="{% url 'instruments:edit_instrument' instrument.id %}">Edit</a>
    <a href="{% url 'instruments:instrument_index' %}">Back to Instrument List</a>
{% endblock %}

{% block content %}
    <table>
        <tr>
            <th>Type:</th>
            <td>{{ instrument.type }}</td>
        </tr>
        <tr>
            <th>Serial Number:</th>
            <td>{{ instrument.serial_num }}</td>
        </tr>
        <tr>
            <th>Maker:</th>
            <td>{{ instrument.maker }}</td>
        </tr>
        <tr>
            <th>Notes:</th>
            <td>{{ instrument.notes }}</td>
        </tr>
    </table>
{% endblock %}